### ISSUE TITLE
ViewPager Wide Image Issue

### ISSUE THREAD

**Issue by pavelaizen** [noties/ScrollingBackgroundView#1]
Hi,

I'm using background image with width larger than ScrollingBackgroundView width.
using ViewPager it always starts from start.
Actually it should continue from last position.

Please help :)

**Comment by noties** [comment]
Hello!

I assume that you are using code sample from sample application. As ViewPager is really specific for indicating scroll, there is no easy way. One solution that comes to my mind is to use real ViewPager width in a OnPageScrolledListener, for example:
```java
if (positionOffsetPixels != 0) {
    final int x = (position * viewPager.getWidth()) + positionOffsetPixels;
    scrollingBackgroundView.scrollTo(x, 0);
}
```

Hope it helps!

**Comment by pavelaizen** [comment]
it helps partially, but background becomes zoomed
As far as I know this is the only endless scroll background view in whole internet :)

**Comment by pavelaizen** [comment]
SOLVED!

instead positionOffsetPixels i used:
```
if (positionOffsetPixels != 0) {
         int x = (int) ((position + positionOffset) * viewPager.getWidth());
           scrollTo(x / 2, 0);
        }
```


also override onSizeChanged
```
    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        int currentItem = viewPager.getCurrentItem();
        scrollTo((currentItem * w) / 2, 0);
    }
```

**Comment by noties** [comment]
Great! Glad we have worked it out! 👍
